# cargo-release configuration
allow-branch = ["main"]
sign-commit = false
sign-tag = false
push-remote = "origin"
pre-release-commit-message = "chore: release {{version}}"
tag-message = "chore: release {{version}}"
tag-prefix = "v"
consolidate-commits = false
